### ISSUE TITLE
change "import pynotifier" to "import py-notifier"

### ISSUE THREAD

**Issue by kafoby** [screamz2k/SCREAMZ-SELFBOT#1]
pip won't find pynotifier. 
update pynotifier to py-notifier in requirements.txt and change `import pynotifier` to `import py-notifier` in main.py and you're golden.

**Comment by kafoby** [comment]
just would like to say, great work otherwise my friend. i tested everything after fixing that typo and it works great.

**Comment by lucahennemann** [comment]
Im very happy about your good feedback and im going to change the mistake rn :)
